### ISSUE TITLE
Audio Static when a 16bit file is in playlist with 24bit file

### ISSUE THREAD

**Issue by shoober420** [DeaDBeeF-Player/deadbeef#1909]
### Steps to reproduce the problem
Have a playlist with both 16bit and 24bit audio files

### What's going on? Describe the problem in as much detail as possible.
When the 16bit song is finished, the 24bit song will play with static
I have the error, I'll post it a little later.

Deadbeef version: Git Master as of October 7th
OS: Arch Linux 64bit

**Comment by Alexey-Yakovenko** [comment]
still the same audio device (non-dmix), which requires 24->32 bit conversion?

**Comment by shoober420** [comment]
Yes. Here is the error.

cannot set parameters (File descriptor in bad state)

Just found something.

16bit to 24bit = static
24bit to 16bit = song played to fast (outputs the same error)

**Comment by Alexey-Yakovenko** [comment]
ok, thanks. will be looking into it

**Comment by Alexey-Yakovenko** [comment]
There was an issue.. I didn't get static/distortion, but the error was there indeed. Added a code to drain the buffers before switching format, and that solved it for me.

Please let me know if it works for you too.

**Comment by shoober420** [comment]
The same behavior and error still occurs. It seems like it doesn't switch to the desired bit rate when it changes mid playlist.

**Comment by shoober420** [comment]
Fixed, thank you sir.

**Comment by Lithopsian** [comment]
Nice.  Seems to have fixed some problems when reconfiguring the resampler during playback.  Playback now continues, although I still see this message:

> cannot set sample format to 32 bps (error: Invalid argument), trying all supported formats
> Found compatible format 16 bps

**Comment by Alexey-Yakovenko** [comment]
well.. getting this message is nice if you really want to know what's going on.. but I will probably remove it at some point to avoid unnecessary buggery from uneducated users.
