### ISSUE TITLE
Album shuffle broken?

### ISSUE THREAD

**Issue by huanie** [DeaDBeeF-Player/deadbeef#2471]
### Steps to reproduce the problem
Enable album shuffle and play an album.

### What's going on? Describe the problem in as much detail as possible.
When the album ends it repeats the album from start. Playing the last track of the album also repeats the album from start.

### Expected behavior:
When the album ends it is supposed to choose a random album to continue.

### Information about the software:
Deadbeef version: 1.8.4-1
OS: Arch Linux

**Comment by Alexey-Yakovenko** [comment]
It's not broken for me, just tried. Can you describe your situation in more details? Does it happen every time in any playlist? Any other things worth mentioning?

**Comment by huanie** [comment]
I was one playlist with my entire library in a folder.
Deadbeef was installed through pacman.

Have you tried to play the last song of the album, you can seek to the end but skipping seems to go to a new random album.

**Comment by gapf2010** [comment]
Have you checked this? https://github.com/DeaDBeeF-Player/deadbeef/issues/2468 I also had trouble making the "shuffle album" option work.

**Comment by Alexey-Yakovenko** [comment]
@huanie Indeed, reproduced. Thanks for the clarification.

**Comment by Alexey-Yakovenko** [comment]
Fixed in 1.8.5-beta2

**Comment by rsekman** [comment]
This bug is still occurring for me on Arch, `1.8.8-1`, following the same steps to reproduce. Using "Next" the expected behaviour is observed, but letting the track play to the end the album is repeated from the start.

**Comment by Alexey-Yakovenko** [comment]
I will verify when I have time.

**Comment by rsekman** [comment]
It may be relevant: unlike the previous reporter, I have several playlists.

**Comment by rsekman** [comment]
The bug only occurs if the album is listened through "naturally". If
Next is ever used, even letting the final track play to the end, a
random album is played subsequently.

**Comment by Alexey-Yakovenko** [comment]
@rsekman I can't reproduce this bug

**Comment by rsekman** [comment]
Did you use Next to skip through the album? If I do this the bug does not occur. To reproduce without having to listen to an entire album

- Double-click the last track of an album in the playlist.
- Skip near the end of the track using the progress bar
- Wait for the track to finish.

I tried this just now on `6e206e20efef`. I attach a screen recording. You can see by the album art and by the marker in the playlist that playback skips to the beginning of the album Rites At Dawn.

https://user-images.githubusercontent.com/29686694/131262031-0a144ea0-6652-4f37-9d07-7b43df706b27.mp4

**Comment by rsekman** [comment]
> Did you use Next to skip through the album? If I do this the bug does not occur. 

Hmm, this seems to be false actually. It's more complicated than this. I will open a new issue.
