### ISSUE TITLE
Notifications stopped working (Deadbeef 1.8.5-1)

### ISSUE THREAD

**Issue by obi-juan88** [DeaDBeeF-Player/deadbeef#2497]
### Steps to reproduce the problem
Just play any song

### What's going on? Describe the problem in as much detail as possible.
I installed new version from deb file on website and notifications stopped altogether. It seems notify.so is missing (at least thats what it says on the log).  I already tried looking for the file at /opt/deadbeef/lib/deadbeef/notify.so and its there.

![Captura de pantalla -2021-01-10 19-18-59](https://user-images.githubusercontent.com/44253536/104140924-a0de3f00-5379-11eb-94bb-51fb5c72788a.png)

### Information about the software:

Deadbeef version: 1.8.5-1
OS: Linux Debian 10 Buster

**Comment by ToadKing** [comment]
You need to install the libdispatch library since it's a new dependency for the plugin. I think it's called `libdispatch0` on Debian.

**Comment by obi-juan88** [comment]
Thanks for the answer, unfortunately libdispatch0 package doesn't exist for Debian Stable branch (only for Sid/ Unstable), and i cannot install that package on stable due to unmet dependencies:

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libdispatch0

Guess i'll downgrade to 1.8.4 for now.

**Comment by Alexey-Yakovenko** [comment]
Thanks for reporting, I forgot to update the package scripts to include libdispatch. Will update and upload the packages as soon as I can.

**Comment by Alexey-Yakovenko** [comment]
It has been fixed, just re-download the packages, the URLs are the same.

**Comment by obi-juan88** [comment]
> It has been fixed, just re-download the packages, the URLs are the same.

I tried to purge package and reinstall package and problem still persist,
Unless its a different URL from:
https://sourceforge.net/projects/deadbeef/files/travis/linux/1.8.5/deadbeef-static_1.8.5-1_amd64.deb/download

**Comment by Alexey-Yakovenko** [comment]
Can you check if you have the file `/opt/deadbeef/lib/libdispatch.so`?

**Comment by obi-juan88** [comment]
Its not there.
![Uploading scrot.png…]()

**Comment by Alexey-Yakovenko** [comment]
wrong folder, it should be one level above..
/opt/deadbeef/lib

**Comment by Alexey-Yakovenko** [comment]
another thing to try:
install the app called `chrpath`, and run this command:
`chrpath /opt/deadbeef/lib/deadbeef/notify.so`
what's the output?

**Comment by obi-juan88** [comment]
The only thing in that folder is the "deadbeef" folder with the content i posted before.
![Captura de pantalla -2021-01-12 14-58-08](https://user-images.githubusercontent.com/44253536/104373936-bf157d80-54e6-11eb-9445-6d5725923ca8.png)



> another thing to try:
> install the app called `chrpath`, and run this command:
> `chrpath /opt/deadbeef/lib/deadbeef/notify.so`
> what's the output?

![chrpat](https://user-images.githubusercontent.com/44253536/104374061-ed935880-54e6-11eb-9ed3-5b6f06e80d95.png)

**Comment by Alexey-Yakovenko** [comment]
uhh.. I just double checked, indeed the files are not in the package. I lost something in the process.
They probably stayed there on my machine from when I was experimenting.
Will try again. sorry for the confusion.

**Comment by Alexey-Yakovenko** [comment]
Rebuilding the packages now

**Comment by obi-juan88** [comment]
Sure thing lemme know when its up again so i can do some testing.

**Comment by Alexey-Yakovenko** [comment]
Should work now

**Comment by obi-juan88** [comment]
Yes it does. Thank you.
