### ISSUE TITLE
Spectrum visualization not using custom background color on start-up until playback is started

### ISSUE THREAD

**Issue by IssueCreator123** [DeaDBeeF-Player/deadbeef#3029]
Not sure if this is a bug or a feature request.

When starting DeaDBeeF, the background color for the Spectrum visualization is black until playback is started, after which it properly uses the custom background color set for visualizations in the settings. However, like the Oscilloscope visualization, I'd like it to use the custom background color immediately after starting DeaDBeeF, not only after playing a song.

DeaDBeeF 1.9.5
Linux Mint 21.2

**Comment by Oleksiy-Yakovenko** [comment]
I believe, updating deadbeef to the latest version should solve this problem for you.

**Comment by IssueCreator123** [comment]
I updated to 1.9.6, but unfortunately to issue still persists.
