### ISSUE TITLE
Some covers do not appear in notification (OSD) in last build

### ISSUE THREAD

**Issue by Npa972** [DeaDBeeF-Player/deadbeef#3044]
### Steps to reproduce the problem
Play a track
Cover appear in OSD in 1.9.6
Cover not appear in last build

### What's going on? Describe the problem in as much detail as possible.
Some covers appears and others not

### Information about the software:
Deadbeef version: last nightly build
OS: arch

Track example :
https://www.dropbox.com/scl/fi/12zmdjdweusasb47td03a/11-Rodney-Jones-Blues-When-You-Need-Them.mp3?rlkey=e8fxvmdgtyxmhhed5mmt1o27w&dl=0

**Comment by Samueru-sama** [comment]
I've also noticed this issue on arch for while. Though it is only with one album. I am on the latest portable devel build. 

I remember the album art in the notifications used to be bigger, then they got smaller and from there is where this issue began to happen.

It never bothered me enough to report it lol: 

https://github.com/DeaDBeeF-Player/deadbeef/assets/36420837/e865a201-36e0-4f66-8ba8-d5201e857436

**Comment by Npa972** [comment]
@Oleksiy The notification issue appears with the latest nightly build.
Covers appears in version 1.9.6
I have more than 2000 albums in my playlist, i can't check all covers but yes it happens with some album.
2 examples : 
https://www.dropbox.com/scl/fi/8x9wq74cds4bsz4w0nx7n/01-silver.mp3?rlkey=m7ra1a12dpqodxx2qa0xqtyke&dl=0
https://www.dropbox.com/scl/fi/12zmdjdweusasb47td03a/11-Rodney-Jones-Blues-When-You-Need-Them.mp3?rlkey=e8fxvmdgtyxmhhed5mmt1o27w&dl=0

**Comment by Oleksiy-Yakovenko** [comment]
Ah, ok -- I see now. I slightly misunderstood the problem. I thought covers were not showing in 1.9.6.
Thanks for clarification. I will check it out.

**Comment by Samueru-sama** [comment]
I think I know why the issue happens.

I was troubleshooting an issue with the notifications of another application, and deadbeef changed the song to one that can't display the album art, and I got this message on my terminal from dunst: 

`WARNING: Expected image data to be of length 12285 but got a length of 12288`

That warning is only shown for the album that doesn't show in the notifications.

**Comment by Oleksiy-Yakovenko** [comment]
thanks for this detail. there's probably an issue with encoding the image for dbus packet.

**Comment by Samueru-sama** [comment]
Hey the issue was fixed in my end, I don't know what did it but the last nightly build doesn't have the issue anymore.

**Comment by Npa972** [comment]
Hi I'm sorry but this issue is still here with the latest nightly build.
**It is ok with 1.9.6.**
The cover is embedded.
Thanks
![image](https://github.com/user-attachments/assets/2ea13525-b08e-40f6-9358-42b5d61eef3b)
